# Generated by Django 4.2.11 on 2024-04-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sari_Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='images/')),
                ('Price', models.TextField()),
            ],
        ),
    ]
