# Generated by Django 4.2.11 on 2024-05-15 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminDashboard', '0006_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100.002, max_digits=10),
        ),
        migrations.CreateModel(
            name='BookingWithKhalti',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=30)),
                ('product_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('pid', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('product_obs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminDashboard.productsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
